/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uy.gruposoft.presentacion;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uy.gruposoft.excepciones.LocalException;
import uy.gruposoft.logica.FachadaLogica;
import uy.gruposoft.logica.Local;
import uy.gruposoft.logica.Locales;

/**
 *
 * @author andressantucci
 */
public class VentanaLocales extends javax.swing.JInternalFrame {

    
    public Local localSeleccionado = new Local();

    /**
     * Creates new form VentanaLocales
     *
     * @throws uy.gruposoft.excepciones.LocalException
     */
    public VentanaLocales() throws LocalException {
        initComponents();
        mostrarLocales();
    }

    public static void mostrarLocales() throws LocalException {

        String[] nombresColumnas = {"nro_local", "negocio", "encargado", "Fecha Alta"};
        Locales locales = FachadaLogica.cargarLocales();
        DefaultTableModel modelo = new DefaultTableModel(null, nombresColumnas) {
        
            public boolean isCellEditable(int row, int col){
                if (col == 0)
                    return false;
                else 
                    return true;
            }
        };
        
        

        Object[] fila = new Object[modelo.getColumnCount()];

        for (int i = 0; i < locales.getLocales().size(); i++) {
            fila[0] = locales.getLocales().get(i).getNumeroLocal();
            fila[1] = locales.getLocales().get(i).getNombreNegocio();
            fila[2] = locales.getLocales().get(i).getEncargado();
            fila[3] = locales.getLocales().get(i).getFechaAlta();

            modelo.addRow(fila);

        }
        tabla.setModel(modelo);

        tabla.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabla.getColumnModel().getColumn(1).setPreferredWidth(60);
        tabla.getColumnModel().getColumn(2).setPreferredWidth(60);
        tabla.getColumnModel().getColumn(3).setPreferredWidth(60);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ingresoNumero = new javax.swing.JTextField();
        negocioTxt2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        encargadoTxt2 = new javax.swing.JTextField();
        insertarUsuario2 = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(1150, 700));
        setMinimumSize(new java.awt.Dimension(1150, 700));
        setPreferredSize(new java.awt.Dimension(1150, 700));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Negocio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Numero");

        ingresoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoLocal2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Negocio");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Encargado");

        encargadoTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encargadoTxt2ActionPerformed(evt);
            }
        });

        insertarUsuario2.setText("Crear Local");
        insertarUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarLocal2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4))
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertarUsuario2)
                    .addComponent(ingresoNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(negocioTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(encargadoTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(negocioTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(encargadoTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133)
                .addComponent(insertarUsuario2)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Buscar por negocio");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista De Locales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 135, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(31, 31, 31)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(modificar)
                        .addGap(18, 18, 18)
                        .addComponent(eliminar)
                        .addGap(36, 36, 36))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modificar)
                            .addComponent(eliminar)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void validarLocal() throws LocalException{
        
        
        String numeroStr = this.ingresoNumero.getText();
        String negocio = this.negocioTxt2.getText();
        String encargado = this.encargadoTxt2.getText();
        
        
        if (numeroStr.compareTo("") != 0 && negocio.compareTo("")!=0 && encargado.compareTo("")!=0)
        {
        
        boolean isNumeric =  numeroStr.matches("[+-]?\\d*(\\.\\d+)?");
        if (isNumeric)
        {   
            int numero = Integer.parseInt(numeroStr);
            
            Local local = new Local();
            
            local.setNumeroLocal(numero);
            local.setNombreNegocio(negocio);
            local.setEncargado(encargado);
            
            if (FachadaLogica.verificarLocal(local)){
                JOptionPane.showMessageDialog(this, " ya existe un local con ese numero, ingrese otro");
            }
            else{
                FachadaLogica.insertarLocal(local);
                JOptionPane.showMessageDialog(this, "El Local se ingreso correctamente");
                mostrarLocales();

            }
             
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Ingrese un caracter valido para el numero del local");            
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Ingrese caracteres validos ");            
          
        }
        
        
    }
            
            
    
    
    
    
    private void insertarLocal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarLocal2ActionPerformed
        try {
            validarLocal();
        } catch (LocalException ex) {
            Logger.getLogger(VentanaDeUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_insertarLocal2ActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        if(txtbuscar.getText().equals("")){
            try {
                mostrarLocales();
            } catch (LocalException ex) {
                Logger.getLogger(VentanaDeUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                buscarLocales();
            } catch (LocalException ex) {
                Logger.getLogger(VentanaDeUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed

        int seleccion = tabla.getSelectedRowCount();

        if (seleccion == 1) {
            if (localSeleccionado.getNombreNegocio() == null) {
                JOptionPane.showMessageDialog(this, "no se modifico ningun registro");
            } else {
                    try {
                        FachadaLogica.modificarLocal(localSeleccionado);

                    } catch (LocalException ex) {
                        Logger.getLogger(VentanaLocales.class.getName()).log(Level.SEVERE, null, ex);

                    }
                    JOptionPane.showMessageDialog(this, "Registro Modificado Correctamente");

                }
              
        }else{
            JOptionPane.showMessageDialog(this, "no hay fila seleccionada");
        }

        
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
        // TODO add your handling code here:

        int seleccion = tabla.getSelectedRowCount();
        try {
            if (seleccion == 1) {
                int res = JOptionPane.showConfirmDialog(null, "¿Desea Eliminar el Registro?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (res == JOptionPane.YES_OPTION) {

                    FachadaLogica.eliminarLocal(localSeleccionado);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe Seleccionar Fila");
            }

        } catch (LocalException ex) {
            Logger.getLogger(VentanaDeUsuario.class.getName()).log(Level.SEVERE, null, ex);

        }

        try {
            mostrarLocales();
        } catch (LocalException ex) {
            Logger.getLogger(VentanaDeUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_eliminarMouseClicked

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int nro = (int) tabla.getValueAt(tabla.getSelectedRow(), 0);
        
        String negocio = tabla.getValueAt(tabla.getSelectedRow(), 1).toString();

        String encargado = tabla.getValueAt(tabla.getSelectedRow(), 2).toString();

        localSeleccionado.setNumeroLocal(nro);
        localSeleccionado.setNombreNegocio(negocio);
        localSeleccionado.setEncargado(encargado);
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyReleased
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {

            int numero = (int) tabla.getValueAt(tabla.getSelectedRow(), 0);

            String negocio = tabla.getValueAt(tabla.getSelectedRow(), 1).toString();

            String encargado = tabla.getValueAt(tabla.getSelectedRow(), 2).toString();


            localSeleccionado.setNumeroLocal(numero);
            localSeleccionado.setNombreNegocio(negocio);
            localSeleccionado.setEncargado(encargado);

        }

    }

        public static boolean caracteresValidos(String datos) {
            return datos.matches("[a-z A-Z]*");
    }//GEN-LAST:event_tablaKeyReleased

    private void encargadoTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encargadoTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encargadoTxt2ActionPerformed

    private void ingresoLocal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoLocal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoLocal2ActionPerformed


    public  void buscarLocales() throws LocalException {

        String[] nombresColumnas = {"nro_local", "negocio", "encargado", "Fecha Alta"};
        
        String buscar = txtbuscar.getText();
        Local local = new Local();
        local.setNombreNegocio(buscar);
        Locales locales = FachadaLogica.buscarLocal(local);
        DefaultTableModel modelo = new DefaultTableModel(null, nombresColumnas);

        Object[] fila = new Object[modelo.getColumnCount()];

        for (int i = 0; i < locales.getLocales().size(); i++) {
            fila[0] = locales.getLocales().get(i).getNumeroLocal();
            fila[1] = locales.getLocales().get(i).getNombreNegocio();
            fila[2] = locales.getLocales().get(i).getEncargado();
            fila[3] = locales.getLocales().get(i).getFechaAlta();

            modelo.addRow(fila);

        }
        tabla.setModel(modelo);

        tabla.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabla.getColumnModel().getColumn(1).setPreferredWidth(60);
        tabla.getColumnModel().getColumn(2).setPreferredWidth(60);
        tabla.getColumnModel().getColumn(3).setPreferredWidth(60);

    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField encargadoTxt2;
    private javax.swing.JTextField ingresoNumero;
    private javax.swing.JButton insertarUsuario2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField negocioTxt2;
    public static javax.swing.JTable tabla;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}

